# Site settings
title: Élevage de Theyssamy
email: info@theyssamy.fr
description: "L'élevage de Theyssamy, situé au haras des Boulaies dans l'Orne, se consacre à l'élevage de chevaux de sport et propose des pensions, cours, sorties en compétitions et balades."
baseurl: ""
url: "http://jkdel.github.io/theyssamy/"
github_username: jkdel
lsi: false
encoding: utf-8

collections:
  elevage:
    output: true
  a_vendre:
    output: true
  actualites:
    output: true

defaults:
  -
    scope:
      type: "elevage"
    values:
      layout: "post"
      js: "they_post.min.js"
  -
    scope:
      type: "a_vendre"
    values:
      layout: "post"
      js: "they_post.min.js"
  -
    scope:
      type: "actualites"
    values:
      layout: "post"
      js: "they_post.min.js"

gems:
  - jekyll-sitemap
